name=Boton
version=0.0.3
author=piruetasxyz
maintainer=piruetasxyz
sentence=Library for handling buttons with microcontrollers
paragraph=Compatible with Arduino and Raspberry Pi Pico.
category=Sensors
url=https://github.com/piruetasxyz/Boton
architectures=*
includes=Boton.h